name: Building Project

# from: https://game.ci/docs/github/getting-started

on: [push, pull_request]

jobs:
  clone: 
    name: Clone the repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      # Build
      - name: Navigate to Subdirectory and Build Project
        run: |
          - name: Build project
            uses: game-ci/unity-builder@v4 
            env:
              UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
              UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            with:
              targetPlatform: StandaloneLinux64
        working-directory: simulator

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
