name: Build Unity project for Linux

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name
  pull_request:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: StandaloneLinux64

    - name: Build Unity project
      run: |
        mkdir Builds
        unity-editor -quit -batchmode -projectPath . -buildLinux64Player "Builds/MyGameLinux"

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux_Build
        path: Builds/MyGameLinux
